apiVersion: batch/v1
kind: Job
metadata:
  name: p1
spec:
  template:
    spec:
      containers:
      - name: p1
        image: gcr.io/easypaking-82ce0/kkbox_game:latest
        command:
        - /bin/sh
        - -c
        - mongodb_url=mongodb://mongo:27017/ npm run gather-data
      restartPolicy: Never
  backoffLimit: 4
